accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path, include

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', views.home, name="home"),
]

djangoshift/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.views.generic.base import TemplateView 

urlpatterns = [
    # path('staff/',include('staff.urls') ),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # path('', TemplateView.as_view(template_name='home.html'), name='home'), # 追加
]

accounts/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class Staff(models.Model):

    id = models.AutoField(verbose_name='社員ID',primary_key=True)
    name=models.ForeignKey(get_user_model(),on_delete=models.CASCADE,max_length=20,blank=False, null=True,verbose_name='User')
    roll = models.CharField(verbose_name='役職',max_length=10, blank=False, null=True)
    nyushabi = models.DateField(verbose_name='入社日',blank=False, null=True)
    taishabi = models.DateField(verbose_name='退社日',blank=True, null=True)
    hyoujijyun = models.IntegerField(verbose_name='表示順',unique=True)
    jikyu = models.IntegerField(verbose_name='時給',blank=False, null=True)
    delete = models.BooleanField(verbose_name='削除フラグ',default=False)
    create_date = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    create_user = models.CharField(verbose_name='登録ユーザ', max_length=50, null=True)
    update_date = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    update_user = models.CharField(verbose_name='更新ユーザ', max_length=50, null=True)

    def __str__(self):
        return str(self.name)

schedule/models.py
from django.db import models
from shisetsu.models import *
from accounts.models import *
from django.contrib.auth import get_user_model


# Create your models here.

class Shift(models.Model):
    id = models.AutoField(verbose_name='シフトID',primary_key=True)
    name = models.CharField(verbose_name='シフト名', max_length=1)
    start_time = models.TimeField(verbose_name="開始時間")
    end_time = models.TimeField(verbose_name="終了時間")
    wrok_time = models.IntegerField(verbose_name='勤務時間')

    def __str__(self):
        return self.name

class Schedule(models.Model):
    id = models.AutoField(verbose_name='スケジュールID',primary_key=True)
    # user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    user=models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    date = models.DateField(verbose_name='日付')
    shift_name_1 = models.ForeignKey(Shift, verbose_name='1シフト名', related_name='shift_name1',on_delete=models.SET_NULL,null= True)
    shisetsu_name_1 = models.ForeignKey(Shisetsu, verbose_name='1施設', related_name='shisetsu_name1',on_delete=models.SET_NULL,blank=True, null=True)
    shift_name_2 = models.ForeignKey(Shift, verbose_name='2シフト名', related_name='shift_name2',on_delete=models.SET_NULL,blank=True, null=True)
    shisetsu_name_2 = models.ForeignKey(Shisetsu, verbose_name='2施設', related_name='shisetsu_name2',on_delete=models.SET_NULL,blank=True, null=True)
    shift_name_3 = models.ForeignKey(Shift, verbose_name='3シフト名', related_name='shift_name3',on_delete=models.SET_NULL,blank=True, null=True)
    shisetsu_name_3 = models.ForeignKey(Shisetsu, verbose_name='3施設', related_name='shisetsu_name3',on_delete=models.SET_NULL,blank=True, null=True)
    shift_name_4 = models.ForeignKey(Shift, verbose_name='4シフト名', related_name='shift_name4',on_delete=models.SET_NULL,blank=True, null=True)
    shisetsu_name_4 = models.ForeignKey(Shisetsu, verbose_name='4施設', related_name='shisetsu_name4',on_delete=models.SET_NULL,blank=True, null=True)
    

shisetsu/models.py
from django.db import models
from colorfield.fields import ColorField

# Create your models here.
class Shisetsu(models.Model):
    id = models.IntegerField(verbose_name='施設ID',primary_key=True)
    name = models.CharField(verbose_name='施設名', max_length=50)
    adress = models.CharField(verbose_name='住所', max_length=100)
    tel = models.CharField(verbose_name='電話番号', max_length=20,null=True,blank=True) 
    fax = models.CharField(verbose_name='FAX番号', max_length=20,null=True,blank=True) 
    color = ColorField(verbose_name='表示色', default='#FF0000')
    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from accounts.models import Staff

# Create your views here.
@login_required
def home(request):

    staff_info=Staff.objects.all()

    staff_dict={'staffs':staff_info}


    return render(request, 'accounts/home.html',context=staff_dict)

schedule/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    {% block customcss %} {% endblock customcss %}

    <title>縁家</title>
  </head>
  <body>
    {%block header%} {%endblock header%} {%block content%} {%endblock content%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/accounts/home.html
{% extends 'accounts/base.html' %} {% load static %} {% block customcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
{% endblock customcss %} {% block header %}
<title>ホーム画面</title>
{% endblock header %} {% block content %}
<body>
  {% if user.is_authenticated %} Hi {{ user.username }}!
  <h2>{{ user.get_full_name }}</h2>
  <ol>
    {% for person in staffs %}
    <ul>
      <li>名前: {{ person.name }}</li>
      <li>役職: {{ person.roll }}</li>
      <li>入社日: {{ person.nyushabi}}</li>
      <li>退社日: {{ person.taishabi }}</li>
      <li>表示順: {{ person.hyoujijyun }}</li>
      <li>時給: {{ person.jikyu }}</li>
      <li>削除フラグ: {{ person.delete }}</li>
      <li>登録日時: {{ person.create_date }}</li>
      <li>登録ユーザー: {{ person.create_user }}</li>
      <li>更新日時: {{ person.update_date }}</li>
      <li>更新ユーザー: {{ person.update_user }}</li>
    </ul>
    {% endfor %}
  </ol>

  <p><a href="{% url 'accounts:logout' %}">logout</a></p>
  {% else %}
  <p>You are not logged in</p>
  <a href="{% url 'accounts:login' %}">login</a>
  {% endif %}
</body>
{% endblock content %}

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}


{% block customcss %}
    <link rel='stylesheet' type='text/css' href="{% static 'css/accounts/style.css' %}">
{% endblock customcss %}


{% block header %}
{% endblock header %}

{% block content %}
  <body>

    <form class="form-login" action='' method='POST'>
    <h1>ログイン画面</h1>
    {% csrf_token %}

    {{ form.as_p }}

    <button>ログイン</button>
    <p class="mt-5 mb-3 text-muted">&copy; 株式会社　Unagui</p>
    </form>
  </body>
</html>
{% endblock content %}

templates/base.html
<!-- <!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    {%block header%}{%endblock header%}{%block content%}{%endblock content%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
<!DOCTYPE html>
<html>
<head>

templates/staff/create.html
{%extends 'base.html'%} {%block title%} {% endblock title %} {% block header %}
スタッフ登録 {%endblock header%} {% block content %}
<from action="" method="POST"
  >{% csrf_token %} {{ form.as_p }}
  <input type="submit" value="登録" />
</from>
{% endblock content %}